.\"                                      Hey, EMACS: -*- nroff -*-
.TH QTDMM 1 "Dec 14, 2006"
.SH NAME
QtDMM \- GUI for Digital Multimeters
.SH SYNOPSIS
.B qtdmm
.SH DESCRIPTION
QtDMM presents a graphical user interface to digital multimeters. It caters
for the loggin of data, its export and the triggering of external applications.
The recorder features manual start, scheduled start (at a given time) and
triggered automatic start when given thresholds are reached. Additionally
you can start an external application when given thresholds are reached.
.SH SEE ALSO
.BR http://www.mtoussaint.de/qtdmm.html
.br
online help of application
.SH AUTHOR
QtDMM was written by Matthias Toussaint.
